# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

includes:
  actions:
    taskfile: tasks/Taskfile-gha.yml
    internal: true
    vars:
      ACT_JOB: '{{.ACT_JOB | default "test"}}'
  sa:
    taskfile: tasks/Taskfile-static.yml
    internal: true
    vars:
      TOOL_DIR: "{{.TOOL_DIR}}"
      GOLANGCI_LINT_VERSION: "{{.GOLANGCI_LINT_VERSION}}"
  clean:
    taskfile: tasks/Taskfile-clean.yml
    internal: true
  format:
    taskfile: tasks/Taskfile-style.yml
    internal: true
    vars:
      TOOL_DIR: "{{.TOOL_DIR}}"
  packages:
    taskfile: tasks/Taskfile-packages.yml
    internal: true
  test: tasks/Taskfile-test.yml

vars:
  GO_VERSION:
    sh: "cat go.mod | awk '/^go / {print $2}'"
  GOLANGCI_LINT_VERSION: v2.8.0
  OUT_DIR: bin # directory to place built binaries
  SRC_DIR: cmd # directory containing source code for main packages
  TOOL_DIR: tools # directory to install development tools
  CLI_BINS: # list of command line binaries to build
    - svc-mon
    - webhook-logger

tasks:
  default:
    aliases: [help]
    desc: show this help message
    silent: true
    cmds:
      - echo "Available tasks:"
      - echo ""
      - task --list
      - echo ""
      - echo "  task --list                  see all tasks"
      - echo "  task --summary <TASK_NAME>   see task details"
      - echo "  task <TASK_NAME>             run specific task"
      - echo ""

  # --------------------------------------------------------
  # Setup tasks
  # --------------------------------------------------------

  setup:
    cmds:
      - mkdir -p {{.OUT_DIR}}
      - task: sa:setup
      - task: format:setup
      - task: packages:get
    desc: prepare the environment (get tools and install dependencies)

  update:
    cmds:
      - task: packages:update
    desc: update dependencies and development tools

  # --------------------------------------------------------
  # Complete project validation tasks
  # --------------------------------------------------------

  validate:
    cmds:
      - task: clean
      - task: format:code
      - task: lint
      - task: test:unit
      - task: test:integration
      - task: build
      - task: test:e2e
    desc: run all checks and tests to validate code health

  # --------------------------------------------------------
  # Styling tasks
  # --------------------------------------------------------

  format:
    cmds:
      - task: format:code
      - task: format:yaml
    desc: format all code and documentation

  format:check:
    cmds:
      - task: format:code:check
      - task: format:yaml:check
      - task: format:docs:check
    desc: check format of all code and documentation

  # --------------------------------------------------------
  # Check tasks
  # --------------------------------------------------------
  lint:
    cmds:
      - task: sa:lint
    desc: run all static analysis checks to validate code health

  # --------------------------------------------------------
  # Test tasks
  # --------------------------------------------------------

  test:
    cmds:
      - task: test:unit
      - task: test:integration
      - task: test:e2e
      - task: test:benchmarks
    desc: run all tests

  # --------------------------------------------------------
  # Build tasks
  # --------------------------------------------------------

  build:
    cmds:
      - for: {var: CLI_BINS}
        task: build:{{.ITEM}}
    desc: build all binaries

  build:*:
    vars:
      EXE: "{{index .MATCH 0}}"
      MAIN_DIR: "{{.SRC_DIR}}/{{.EXE}}"
    cmds:
      - mkdir -p '{{.OUT_DIR}}'
      - go build -o '{{.OUT_DIR}}/{{.EXE}}' './{{.MAIN_DIR}}'
    sources:
      - "./cmd/**/*.go"
      - "./internal/**/*.go"
      - "go.sum"
      - exclude: "**/*_test.go"
    generates:
      - "{{.OUT_DIR}}/{{.EXE}}"
    desc: build the main binary
    summary: |
      Build the main binary for this application

  # --------------------------------------------------------
  # Clean
  # --------------------------------------------------------
  clean:
    cmds:
      - task: clean:crumbs
      - task: clean:test-artifacts
    desc: clean all build and test artifacts

  # --------------------------------------------------------
  # Other
  # --------------------------------------------------------

  todo:
    cmds:
      - find . -name '*.go' -o -name '*.sh' -print0 | xargs -0 grep -E '#.*(FIXME|DEBUG|TODO|HACK|TEMP)' || echo "No TODO/FIXME comments found"
    desc: list TODO and FIXME comments
