# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  TOOL_DIR: '{{.TOOL_DIR | default "tools"}}'

tasks:
  default:
    cmds:
      - task: lint
      - task: vet
      - task: staticcheck
    desc: run all static analysis checks to validate code health

  lint:
    cmds:
      - "{{.TOOL_DIR}}/golangci-lint run './...'"
    desc: run the code linter

  vet:
    cmds:
      - go vet './...'
    desc: run go vet to check for suspicious constructs

  staticcheck:
    cmds:
      - "{{.TOOL_DIR}}/staticcheck -checks all './...'"
    desc: run staticcheck to find bugs and performance issues
