# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  TOOL_DIR: '{{.TOOL_DIR | default "tools"}}'

tasks:
  setup:
    cmds:
      - mkdir -p {{.TOOL_DIR}}
      - curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b {{.TOOL_DIR}} {{.GOLANGCI_LINT_VERSION}}
    env:
      GOBIN: "{{joinPath .ROOT_DIR .TOOL_DIR}}"
    desc: install static code analysis tools

  lint:
    cmds:
      - "{{.TOOL_DIR}}/golangci-lint run './...'"
    desc: run the code linter
