# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:

  setup:
    cmds:
      - mkdir -p {{.TOOL_DIR}}
      - go install github.com/google/yamlfmt/cmd/yamlfmt@latest
    env:
      GOBIN: "{{joinPath .ROOT_DIR .TOOL_DIR}}"
    desc: install formatting tools

  code:
    cmds:
      - go fmt ./...
    desc: format Go code

  code:check:
    cmds:
      - true
    desc: check format of Go code

  docs:
    cmds:
      - prettier --write '**/*.md'
    ignore_error: true
    desc: format documentation files

  docs:check:
    cmds:
      - prettier --check ./**/*.md
    ignore_error: true
    desc: check format of documentation files

  yaml:
    cmds:
      - '{{.TOOL_DIR}}/yamlfmt -w .'
    desc: format YAML files

  yaml:check:
    cmds:
      - '{{.TOOL_DIR}}/yamlfmt --lint -q .'
    desc: check format of YAML files
