# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  OUT_DIR: '{{.OUT_DIR | default "bin"}}'
  TOOL_DIR: '{{.TOOL_DIR | default "tools"}}'

tasks:
  crumbs:
    cmds:
      - find . -type f -maxdepth 1 -name "*.log*" -delete
    desc: clean artifacts created by the application

  build-artifacts:
    cmds:
      - rm -f {{.OUT_DIR}}/*
    desc: clean build artifacts

  test-artifacts:
    cmds:
      - rm -f ./coverage.out ./coverage.html
    desc: clean test artifacts

  tooling-artifacts:
    cmds:
      - rm -rf {{.TOOL_DIR}}/*
    desc: clean tooling artifacts, binaries, and caches

  full:
    cmds:
      - task: build-artifacts
      - task: crumbs
      - task: tooling-artifacts
      - task: test-artifacts
    desc: clean all artifacts
