---
name: Build and Release- Go
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Build, test and release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Install Taskfile
        uses: go-task/setup-task@v1
        with:
          version: 3.46.x

      - name: Prepare environment
        run: task setup

      - name: Build binaries
        run: task build

      - name: Release
