---
name: Continuous Integration - Go
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Install Taskfile
        uses: go-task/setup-task@v1
        with:
          version: 3.46.x

      - name: Prepare environment
        run: task setup

      - name: Check formatting
        run: task format:check

      - name: Static analysis
        run: task lint

      - name: Unit tests
        run: task test:unit

      - name: Integration tests
        run: task test:integration

      - name: Build
        run: task build

      - name: End-to-end tests
        run: task test:e2e
