name: Continuous Integration - Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: |
            README.md
            docs/*.md
        continue-on-error: true

      - uses: JustinBeckwith/linkinator-action@v2
        with:
          paths: "*.md"
          timeout: 60000
        continue-on-error: true

  test:
    name: Test on Go ${{ matrix.go-version }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.25]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install Taskfile
        uses: go-task/setup-task@v1
        with:
          version: 3.46.x

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Prepare environment
        run: task setup

      - name: Check code formatting
        run: task format:code

      - name: Static analysis
        run: task check

      - name: Unit tests
        run: task test:unit

      - name: Integration tests
        run: task test:integration

      - name: Build
        run: task build

      - name: End-to-end tests
        run: task test:e2e
