---
name: Continuous Integration - Markdown
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: '**.md'
        continue-on-error: true

      - uses: JustinBeckwith/linkinator-action@v2
        with:
          paths: '**.md'
          timeout: 60000
        continue-on-error: true
